export const FETCH_COCKTAILS_START="FETCH_COCKTAIL_START";
export const FETCH_COCKTAILS_SUCCESS="FETCH_COCKTAIL_SUCCESS";
export const FETCH_COCKTAILS_FAIL="FETCH_COCKTAIL_FAIL";
export const SEARCH_COCKTAIL_START="SEARCH_COCKTAIL_START";
export const SEARCH_COCKTAIL_SUCCESS="SEARCH_COCKTAIL_SUCCESS";
export const SEARCH_COCKTAIL_FAIL="SEARCH_COCKTAIL_FAIL";
